variables:
  npm_config_fund: "false"
  npm_config_audit: "false"
  FF_USE_FASTZIP: "true"

default:
  image: node:16

stages:
  - build
  - test

Server Build:
  stage: build
  script:
    - cd server
    - npm ci
    - npm run update-resolver-types && git diff --quiet
    - npm run check-format
    - npm run lint
    - npm run build

Client Build:
  stage: build
  script:
    - cd client
    - npm ci
    - npm run check-format
    - npm run lint
    - npm run build

Client Test:
  stage: test
  script:
    - cd client
    - npm ci
    - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
